services:
  - type: web
    name: tryyel-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tryyel-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

databases:
  - name: tryyel-db
    plan: free
    databaseName: tryyel
    user: tryyel
